# Generated by Django 4.0 on 2021-12-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_video_filename',
            new_name='original_url',
        ),
    ]
